### ISSUE TITLE
 require cycle node_modules\react-native-canvas

### ISSUE THREAD

**Issue by NikhilMasurkar** [iddan/react-native-canvas#313] opened 2023-04-13 07:40 UTC
I always get this warning message how can i fixed it 

C:\Project_Repo\App_Frontend\IndigoLearn\node_modules\react-devtools-core\dist\backend.js:12506 Require cycle: node_modules\react-native-canvas\dist\Canvas.js -> node_modules\react-native-canvas\dist\Image.js -> node_modules\react-native-canvas\dist\Canvas.js

**Comment by iddan** [comment] 2023-04-25 09:37
Duplicate of #185

**Closed by iddan** 2023-04-25 09:37 UTC
